services:
  app-jti-spot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-jti-spot
    env_file:
      - .env
    depends_on:
      postgres-db-jti-spot:
        condition: service_healthy
    networks:
      - jti-spot-network
    volumes:
    - public_data:/var/www/html/public
    restart: always

  web-jti-spot:
    image: nginx:alpine
    container_name: web-jti-spot
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./docker/nginx/jti-spot.conf:/etc/nginx/conf.d/default.conf
      - public_data:/var/www/html/public
    depends_on:
      - app-jti-spot
    networks:
      - jti-spot-network
    restart: always

  postgres-db-jti-spot:
    image: postgres:15-alpine
    container_name: postgres-db-jti-spot
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$DB_USERNAME -d $$DB_DATABASE"] 
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - jti-spot-network
    restart: always

networks:
  jti-spot-network:
    driver: bridge

volumes:
  postgres_data:
  public_data:
